### ISSUE TITLE
forced_mean table check legal?

### ISSUE THREAD

**Issue by awe2** [uiucsn/astro_ghost#16]
Howdy Alex, as part of getting the photoz_helper to work, I needed to modify PS1QueryFunctions to allow table = 'forced_mean' with release = 'dr2' ; I saw that doing so was a "legal" operation, insofar as it is returns values. Wanted to double check that this is what you mean by 'legal'.

**Comment by alexandergagliano** [comment]
@awe2 I've confirmed on my end that forced_mean is indeed an existing table in dr2, and released a fix as v2.0.2 on pip and github.
