### ISSUE TITLE
GLADE host associations don't return PS1 catalog features

### ISSUE THREAD

**Issue by patrickaleo** [uiucsn/astro_ghost#23]
(For most recent version `2.0.8`)
 Successful GLADE galaxy associations return only these features to hosts from `getTransientHosts()`: 
 ```
Index(['raMean', 'decMean', 'Dist', 'Bmag', 'BmagHyp', 'ImagHyp', 'modzHyp',
       'mod0Hyp', 'logd25Hyp', 'logr25Hyp', 'logdcHyp', 'PAHyp', 'BmagHypC',
       'ImagHypC', 'U-BHypC', 'B-VHypC', 'Jmag2', 'Hmag2', 'Kmag2', 'a_b',
       'PAK', 'BmagGWGC', 'maj', 'min', 'PAGWGC', 'DistGWGC', 'Kmag2MPZ',
       'Bmag2MPZ', 'zsp2MPZ', 'zph2MPZ', 'Flag', 'MajorRad', 'MinorRad',
       'NED_name', 'NED_type', 'NED_vel', 'NED_redshift', 'NED_mag',
       'NED_redshift_flag', 'dist/DLR', 'dist', 'TransientRA', 'TransientDEC',
       'TransientClass', 'GLADE_redshift', 'GLADE_redshift_flag',
       'GLADE_source'],
      dtype='object')
 ```
and not the usual PS1 catalog level features found here: https://outerspace.stsci.edu/display/PANSTARRS/PS1+Database+object+and+detection+tables

Secondarily, if the host matching is found via the parent/sibling hierarchical search, a few PS1 features GHOST internally calculates are not returned:
```
{'yApMag_yKronMag', 'zApMag_zKronMag', 'iApMag_iKronMag', '7DCD', 'i-z', 'rApMag_rKronMag', 'gApMag_gKronMag'}
```

**Comment by alexandergagliano** [comment]
@patrickaleo In the most recent released version of the code (2.0.10) I've added a crossmatch between GLADE and PS1, but we should do some tests to make sure it's finding the right source. I've also added in the additional color and shape features you mention. Could you send me some subset of the transients you're using the code for?

Given your concerns about timing, I've also decreased the GLADE search radius from 1deg (which is probably overkill) to 0.2deg. I've also added a flag for the GLADE search - you can turn it off by running 

```
getTransientHosts(snName, snCoord, GLADE=False, verbose=True)
```
For what it's worth, for a random sample of 10 transients, the code finds 5 hosts in GLADE; it takes ~5s per transient with the 0.2deg search radius, ~7s per transient with GLADE turned off, and ~18s per transient with the original 1.0deg search radius in GLADE. So you might see a speedup if many of your sources are low-redshift.

I'll close the issue for now - feel free to re-open if you have any problems with the newest version!

**Comment by alexandergagliano** [comment]
Re-opening after finding a failure mode, @patrickaleo could you try again with a fresh install?

**Comment by patrickaleo** [comment]
Version `0.2.12` fixes the above issues. Thank you!
