### ISSUE TITLE
RemoteDisconnected for catalog=[“VII/275/glade1"]

### ISSUE THREAD

**Issue by jeqcho** [uiucsn/astro_ghost#29]
**How:** Pressing “Requery broker” for a new set of transients after creating a project
**What:** raise RemoteDisconnected(“Remote end closed connection without”
urllib3.exceptions.ProtocolError: (‘Connection aborted.’, RemoteDisconnected(‘Remote end closed connection without response’))

This is tracked to /site-packages/astro_ghost/DLR.py, line 418, in chooseByGladeDLR
    result = Vizier.query_region(SkyCoord(ra=ra_SN, dec=dec_SN,unit=(u.deg, u.deg),frame=‘icrs’),radius=Angle(0.2, “deg”), catalog=[“VII/275/glade1"])

I can’t track further because the Vizier object seem to have only the function query_region_async and not query_region. But I think the main issue is that sometimes the server are not responding to the GLADE requests. After a few more attempts it finally works, so it is likely a server issue on their side.

**Comment by alexandergagliano** [comment]
@jeqcho I've now packaged up a small version of the GLADE catalog with the `astro_ghost` package so that Vizier is not queried. Could you try re-running for your set of transients with the latest release (github or pip) to verify that it runs without issue?

**Comment by jeqcho** [comment]
Thanks! The issue is resolved.
